### ISSUE TITLE
some similar code of mine for you to consider

### ISSUE THREAD

**Issue by max-mapper** [tmcw/live-require#1]
``` js
;function loadScript(src, cb) {
  if (!cb || typeof(cb) !== "function") cb = function(){}
  if (document.readyState == 'complete' || document.readyState == 'interactive' || document.readyState == 'loaded') {
    var script = document.createElement('script');
    script.onload = cb
    script.src = src
    document.getElementsByTagName('head')[0].appendChild(script)
  } else {
    var line = '<script type="text/javascript" charset="utf-8" src="' + src + '"></script>';
    document.writeln(line);
    cb()
  }
}
```

**Comment by tmcw** [comment]
sweet, thx! where is this from?

**Comment by tmcw** [comment]
And what's the rationale for checking for the document's readyState?

**Comment by max-mapper** [comment]
conglomerated from the wikimedia mobile app, cordova.js (phonegap) and used
in http://gather.at (private repo)

**Comment by max-mapper** [comment]
IIRC if the page hasn't emitted DOMContentLoaded and you try to rely on
.onload it doesnt work in all browsers... its been a while though so I dont
remember the details

**Comment by max-mapper** [comment]
more details: https://github.com/wikimedia/WikipediaMobile/blob/master/assets/www/js/platform-stub.js

**Comment by max-mapper** [comment]
oh wait that just works on doc 'startup'. anyway, I dont remember the cases in which this is needed but at least its in the issues already in case it ever gets encountered :D

**Comment by tmcw** [comment]
Thanks! Added this ticket to see also in the readme https://github.com/tmcw/live-require/blob/master/README.md#see-also
